<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Implementations\" />
    <Folder Include="Global\" />
    <Folder Include="MappingProfiles\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\LibraryManagement.Domain.csproj" />
    <ProjectReference Include="..\Services.Abstraction\LibraryManagement.Services.Abstraction.csproj" />
  </ItemGroup>

</Project>
